# Q7. Add a static method to Car class that return general description for car

class Car:
    no_of_car_created = 0

    def __init__(self, brand, model):
        self.__brand = brand
        self.model = model

        Car.no_of_car_created = Car.no_of_car_created + 1


    def full_name(self):
        return f"{self.__brand} {self.model}"
    
    def get_brand(self):
        return self.__brand
    
    def fuel_type(self):
        return "Petrol and Diesel"
    
    @staticmethod
    def general_description():
        return "This Is Generated By Car Class "
    

class ElectricCar(Car):
    def __init__(self, brand, model, battry_size):
        super().__init__(brand, model)
        self.battry_size = battry_size

    def fuel_type(self):
        return "Electric Charge"


my_Car_obj = Car("Tata", 'Safari')
print(my_Car_obj.general_description())
print(Car.general_description())