# Q9. Use Property Decorator in the car class to make the model attribute read only.

class Car:
    no_of_car_created = 0

    def __init__(self, brand, model):
        self.__brand = brand
        self.__model = model

        Car.no_of_car_created = Car.no_of_car_created + 1


    def full_name(self):
        return f"{self.__brand} {self.__model}"
    
    def get_brand(self):
        return self.__brand
    
    def fuel_type(self):
        return "Petrol and Diesel"
    
    @staticmethod
    def general_description():
        return "This Is Generated By Car Class "
    
    @property
    def model(self):
        return self.__model
    

class ElectricCar(Car):
    def __init__(self, brand, model, battry_size):
        super().__init__(brand, model)
        self.battry_size = battry_size

    def fuel_type(self):
        return "Electric Charge"


my_Car_obj = Car("Tata", 'Safari')
# my_Car_obj.model = 'Safari-2' # return error because we want to access a private variable
print(my_Car_obj.model)


# Note : When we want we can't change any variable/property and user can see only this variable/Property, then first we make private to variable after that we create a method with same variable name and wrap insde the @property decorator