# Q9. Demonstrate the use of isinstance() to check if my_tesla is an instance of Car and ElectricCar.

class Car:
    no_of_car_created = 0

    def __init__(self, brand, model):
        self.__brand = brand
        self.__model = model

        Car.no_of_car_created = Car.no_of_car_created + 1


    def full_name(self):
        return f"{self.__brand} {self.__model}"
    
    def get_brand(self):
        return self.__brand
    
    def fuel_type(self):
        return "Petrol and Diesel"
    
    @staticmethod
    def general_description():
        return "This Is Generated By Car Class "
    
    @property
    def model(self):
        return self.__model
    

class ElectricCar(Car):
    def __init__(self, brand, model, battry_size):
        super().__init__(brand, model)
        self.battry_size = battry_size

    def fuel_type(self):
        return "Electric Charge"
    
my_electric_car = ElectricCar('Tesla', 'Model S', '85kWh')
my_car = Car('Tata', 'Safari')

print(isinstance(my_electric_car, Car))
print(isinstance(my_electric_car, ElectricCar))

print(isinstance(my_car, Car))
print(isinstance(my_car, ElectricCar))