# Q10. Create two class Battery and Engine, and let the ElectricCar class inherit from both, demonstrating multiple inheritance

class Car:
    no_of_car_created = 0

    def __init__(self, brand, model):
        self.__brand = brand
        self.__model = model

        Car.no_of_car_created = Car.no_of_car_created + 1


    def full_name(self):
        return f"{self.__brand} {self.__model}"
    
    def get_brand(self):
        return self.__brand
    
    def fuel_type(self):
        return "Petrol and Diesel"
    
    @staticmethod
    def general_description():
        return "This Is Generated By Car Class "
    
    @property
    def model(self):
        return self.__model

class Battery:
    def battery_info(self):
        return "This is battery"

class Engine:
    def engine_info(self):
        return "This is Engine"

class ElectricCar(Battery, Engine, Car):
    pass

my_car = ElectricCar('Tesla', 'Brand S')
print(my_car.battery_info())
print(my_car.engine_info())